accounts/urls.py
from django.urls import path

from .views import AccountDetailView, AccountUpdateView, SignUpView

app_name = "accounts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("update/", view=AccountUpdateView.as_view(), name="update"),
    path("<str:username>/", view=AccountDetailView.as_view(), name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("annotate/", include("retimgann.urls")),
    path("evaluate/", include("retimgeval.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Retinal Image Tools{% endblock title %}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  
</head>
<body>
    <div class="container">
        <header class="p-3 mb-3 border-bottom">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center
          justify-content-lg-start">
                    <a class="navbar-brand" href="/" style="font-size: 24px;">Retinal Image Tools</a>
                    {% if user.is_authenticated %}
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
            mb-md-0">
                    </ul>
                    <div class="dropdown text-end">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                            <li><a class="dropdown-item" href="{% url 'accounts:detail' user.username %}">Profile </a></li>
                            <li><a class="dropdown-item" href="{% url 'password_change'%}">Change password</a></li>
                            <li>
                                <form action="{% url 'logout' %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item" style="border: none; background: none;">Log Out</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                    {% else %}
                    <div class="text-end">
                        <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log
                            In</a>
                        <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Sign Up</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </header>

        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </div>
    <!-- Bootstrap JavaScript Bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>