config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
    path("annotate/", include("retimgann.urls")),
    path("evaluate/", include("retimgeval.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

# app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retimgann/urls.py
from django.urls import path

from . import views

app_name = "retimgann"

urlpatterns = [
    path("task/<int:task_id>/<int:image_id>", views.annotate, name="annotate"),
    path("annotate_submit/", views.annotate_submit, name="annotate_submit"),
    path("thank_you/", views.thank_you, name="thank_you"),
    path("task/<int:task_id>/", views.task_selection, name="task_selection"),
    path(
        "task/<int:task_id>/instruction/",
        views.task_instruction,
        name="task_instruction",
    ),
]

retimgeval/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "retimgeval"
urlpatterns = [
    path(
        "<str:alias>/instruction/",
        views.TaskInstructionView.as_view(),
        name="task_instruction",
    ),
    path(
        "<str:slug>/",
        views.question_detail,
        name="question_detail",
    ),
    path("<str:alias>/thanks/", views.ThankYouPageView.as_view(), name="thank_you"),
]

pages/templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Retinal Image Tools{% endblock %}

{% block content %}

{% if user.is_authenticated %}

{% comment %} <div class="mb-2">
  <h2 class="d-inline-block me-3">Decision support through AI-generated images</h2>
</div> {% endcomment %}

{% comment %} <div class="mb-2">
  <h4 class="d-inline-block me-3">Fundus</h4>
</div>

<ul class="list-group">
  {% for task in evalutation_tasks %}
    {% if task.category == "realism-fundus" %}
      {% if task.is_active %}
        <li class="list-group-item">
            <a href="{% url 'retimgeval:task_instruction' task.alias %}" class="text-decoration-none">{{ task.description }}</a> 
        </li>
      {% endif %}
    {% endif %}
  {% endfor %}
</ul> {% endcomment %}

{% comment %} <div class="mt-3 mb-2">
  <h4 class="d-inline-block me-3">OCT</h4>
</div>

<ul class="list-group">
  {% for task in evalutation_tasks %}
    {% if task.category == "realism-oct"%}
      {% if task.is_active %}
        <li class="list-group-item">
            <a href="{% url 'retimgeval:task_instruction' task.alias %}" class="text-decoration-none">{{ task.description }}</a> 
        </li>
      {% endif %}
    {% endif %}
  {% endfor %}
</ul>  {% endcomment %}

<div class="mt-4">
  <h2 class="d-inline-block me-3">Decision support through sparse BagNets</h2>
</div>
<ul class="list-group">
  {% comment %} {% for task in annotation_tasks %}
    {% if task.is_active  %}
      {% if "bagnet" in task.category or "annotate" in task.category %}
        <li class="list-group-item">
          <a href="{% url 'retimgann:task_instruction' task.id %}" class="text-decoration-none">{{ task.title }}</a>
        </li> 
      {% endif %}
    {% endif %}
  {% endfor %} {% endcomment %}
  {% for task in evalutation_tasks %}
    {% if "bagnet" in task.category %}
      {% if task.is_active %}
        <li class="list-group-item">
            <a href="{% url 'retimgeval:task_instruction' task.alias %}" class="text-decoration-none">{{ task.description }}</a>
        </li>
      {% endif %}
    {% endif %}
    {% if task.category == "erm-oct" or task.category == "erm-macula" %}
        {% if task.is_active %}
            <li class="list-group-item">
                <a href="{% url 'retimgeval:task_instruction' task.alias %}" class="text-decoration-none">{{ task.description }}</a> 
            </li>
        {% endif %}
    {% endif %}
  {% endfor %}
</ul>

{% else %}

  <p>You are not logged in yet.</p>
        
{% endif %}

{% endblock %}